// Code generated by ogen, DO NOT EDIT.
package oas

type DnsBackResolveRes interface {
	dnsBackResolveRes()
}

type DnsResolveRes interface {
	dnsResolveRes()
}

type EmulateMessageRes interface {
	emulateMessageRes()
}

type ExecGetMethodRes interface {
	execGetMethodRes()
}

type GetAccountRes interface {
	getAccountRes()
}

type GetAccountTransactionsRes interface {
	getAccountTransactionsRes()
}

type GetAllAuctionsRes interface {
	getAllAuctionsRes()
}

type GetBlockRes interface {
	getBlockRes()
}

type GetBlockTransactionsRes interface {
	getBlockTransactionsRes()
}

type GetConfigRes interface {
	getConfigRes()
}

type GetDomainBidsRes interface {
	getDomainBidsRes()
}

type GetEventRes interface {
	getEventRes()
}

type GetEventsByAccountRes interface {
	getEventsByAccountRes()
}

type GetJettonInfoRes interface {
	getJettonInfoRes()
}

type GetJettonsBalancesRes interface {
	getJettonsBalancesRes()
}

type GetMasterchainHeadRes interface {
	getMasterchainHeadRes()
}

type GetNftCollectionRes interface {
	getNftCollectionRes()
}

type GetNftCollectionsRes interface {
	getNftCollectionsRes()
}

type GetNftItemsByAddressesRes interface {
	getNftItemsByAddressesRes()
}

type GetNftItemsByOwnerRes interface {
	getNftItemsByOwnerRes()
}

type GetRawAccountRes interface {
	getRawAccountRes()
}

type GetSubscriptionsByAccountRes interface {
	getSubscriptionsByAccountRes()
}

type GetTraceRes interface {
	getTraceRes()
}

type GetTracesByAccountRes interface {
	getTracesByAccountRes()
}

type GetTransactionRes interface {
	getTransactionRes()
}

type GetValidatorsRes interface {
	getValidatorsRes()
}

type PoolsByNominatorsRes interface {
	poolsByNominatorsRes()
}

type SendMessageRes interface {
	sendMessageRes()
}

type StackingPoolInfoRes interface {
	stackingPoolInfoRes()
}

type StackingPoolsRes interface {
	stackingPoolsRes()
}
