// Code generated by ogen, DO NOT EDIT.
package oas

type DnsBackResolveRes interface {
	dnsBackResolveRes()
}

type DnsInfoRes interface {
	dnsInfoRes()
}

type DnsResolveRes interface {
	dnsResolveRes()
}

type EmulateMessageToAccountEventRes interface {
	emulateMessageToAccountEventRes()
}

type EmulateMessageToEventRes interface {
	emulateMessageToEventRes()
}

type EmulateMessageToTraceRes interface {
	emulateMessageToTraceRes()
}

type EmulateWalletMessageRes interface {
	emulateWalletMessageRes()
}

type ExecGetMethodRes interface {
	execGetMethodRes()
}

type GetAccountInfoByStateInitRes interface {
	getAccountInfoByStateInitRes()
}

type GetAccountRes interface {
	getAccountRes()
}

type GetAccountSeqnoRes interface {
	getAccountSeqnoRes()
}

type GetAccountStateLiteServerRes interface {
	getAccountStateLiteServerRes()
}

type GetAccountTransactionsRes interface {
	getAccountTransactionsRes()
}

type GetAccountsRes interface {
	getAccountsRes()
}

type GetAllAuctionsRes interface {
	getAllAuctionsRes()
}

type GetAllShardsInfoLiteServerRes interface {
	getAllShardsInfoLiteServerRes()
}

type GetBlockHeaderLiteServerRes interface {
	getBlockHeaderLiteServerRes()
}

type GetBlockLiteServerRes interface {
	getBlockLiteServerRes()
}

type GetBlockProofLiteServerRes interface {
	getBlockProofLiteServerRes()
}

type GetBlockRes interface {
	getBlockRes()
}

type GetBlockTransactionsRes interface {
	getBlockTransactionsRes()
}

type GetConfigAllLiteServerRes interface {
	getConfigAllLiteServerRes()
}

type GetConfigRes interface {
	getConfigRes()
}

type GetDnsExpiringRes interface {
	getDnsExpiringRes()
}

type GetDomainBidsRes interface {
	getDomainBidsRes()
}

type GetEventRes interface {
	getEventRes()
}

type GetEventsByAccountRes interface {
	getEventsByAccountRes()
}

type GetItemsFromCollectionRes interface {
	getItemsFromCollectionRes()
}

type GetJettonInfoRes interface {
	getJettonInfoRes()
}

type GetJettonsBalancesRes interface {
	getJettonsBalancesRes()
}

type GetJettonsHistoryByIDRes interface {
	getJettonsHistoryByIDRes()
}

type GetJettonsHistoryRes interface {
	getJettonsHistoryRes()
}

type GetJettonsRes interface {
	getJettonsRes()
}

type GetListBlockTransactionsLiteServerRes interface {
	getListBlockTransactionsLiteServerRes()
}

type GetMasterchainHeadRes interface {
	getMasterchainHeadRes()
}

type GetMasterchainInfoExtLiteServerRes interface {
	getMasterchainInfoExtLiteServerRes()
}

type GetMasterchainInfoLiteServerRes interface {
	getMasterchainInfoLiteServerRes()
}

type GetNftCollectionRes interface {
	getNftCollectionRes()
}

type GetNftCollectionsRes interface {
	getNftCollectionsRes()
}

type GetNftItemByAddressRes interface {
	getNftItemByAddressRes()
}

type GetNftItemsByAddressesRes interface {
	getNftItemsByAddressesRes()
}

type GetNftItemsByOwnerRes interface {
	getNftItemsByOwnerRes()
}

type GetPublicKeyByAccountIDRes interface {
	getPublicKeyByAccountIDRes()
}

type GetRatesRes interface {
	getRatesRes()
}

type GetRawAccountRes interface {
	getRawAccountRes()
}

type GetSearchAccountsRes interface {
	getSearchAccountsRes()
}

type GetShardBlockProofLiteServerRes interface {
	getShardBlockProofLiteServerRes()
}

type GetShardInfoLiteServerRes interface {
	getShardInfoLiteServerRes()
}

type GetStateLiteServerRes interface {
	getStateLiteServerRes()
}

type GetStorageProvidersRes interface {
	getStorageProvidersRes()
}

type GetSubscriptionsByAccountRes interface {
	getSubscriptionsByAccountRes()
}

type GetTimeLiteServerRes interface {
	getTimeLiteServerRes()
}

type GetTonConnectPayloadRes interface {
	getTonConnectPayloadRes()
}

type GetTraceRes interface {
	getTraceRes()
}

type GetTracesByAccountRes interface {
	getTracesByAccountRes()
}

type GetTransactionByMessageHashRes interface {
	getTransactionByMessageHashRes()
}

type GetTransactionRes interface {
	getTransactionRes()
}

type GetTransactionsLiteServerRes interface {
	getTransactionsLiteServerRes()
}

type GetValidatorsRes interface {
	getValidatorsRes()
}

type GetWalletBackupRes interface {
	getWalletBackupRes()
}

type GetWalletsByPublicKeyRes interface {
	getWalletsByPublicKeyRes()
}

type PoolsByNominatorsRes interface {
	poolsByNominatorsRes()
}

type ReindexAccountRes interface {
	reindexAccountRes()
}

type SendMessageLiteServerRes interface {
	sendMessageLiteServerRes()
}

type SendMessageRes interface {
	sendMessageRes()
}

type SetWalletBackupRes interface {
	setWalletBackupRes()
}

type StakingPoolHistoryRes interface {
	stakingPoolHistoryRes()
}

type StakingPoolInfoRes interface {
	stakingPoolInfoRes()
}

type StakingPoolsRes interface {
	stakingPoolsRes()
}

type TonConnectProofRes interface {
	tonConnectProofRes()
}
