name: Create a pull request to update TonAPI SDK

on: workflow_dispatch

jobs:
  update_sdk:
    name: Update TonAPI SDK
    runs-on: ubuntu-latest
    steps:
       - name: create pull request
         run: make update-sdk
    env:
      GH_TOKEN: ${{ github.token }}
